### PR TITLE
Auto create rooms

### PR DESCRIPTION
**Pull request by bryanrite**
Currently a WIP.

Start of auto creation of rooms but before I go further we need more discussion on the topic. 
- Do we want rooms to be accessed via their name (parameterized slug version) rather than ID? 
- How do we want to approach room security, or is that not a concern for the engine and best left to overriding the controller in the parent app?

### CODE REVIEW

**Comment by bklang** [comment]
> Il giorno Jul 20, 2015, alle ore 8:50 AM, Bryan Rite notifications@github.com ha scritto:
> 
> Current a WIP.
> 
> Start of auto creation of rooms but before I go further we need more discussion on the topic.
> 
> Do we want rooms to be accessed via their name (parameterized slug version) rather than ID?

Parameterized slug is preferable. 

> How do we want to approach room security, or is that not a concern for the engine and best left to overriding the controller in the parent app?

Leave this up to the app.

**Comment by bryanrite** [comment]
Ok, this allows specifying the name of a room directly via the URL. It'll parameterize into a slug and titleize into a name:

screen shot 2015-07-22 at 10 50 31 pm
screen shot 2015-07-22 at 10 50 49 pm

Including random stuff:

screen shot 2015-07-22 at 10 51 26 pm
screen shot 2015-07-22 at 10 51 40 pm

And the index routes properly to the named routes and doesn't use the ID at all anymore.

This also removed the "last used" time field when creating rooms... as thats weird, so it handles the situation where a room has never been used and removes that field from the New Room form.

I would suggest from here we make the New Room an inline form rather than its own page since the name is the only thing we ask for.

**Comment by bryanrite** [comment]
Also, setting the title specifically (via new room form) allows you to set the title to whatever you want.
screen shot 2015-07-22 at 11 06 54 pm
screen shot 2015-07-22 at 11 06 59 pm

**Comment by bklang** [comment]
Bug: Joining a room by ID causes a room with that ID to be created.

Example: I had a room named "Thing", id: 1 with no slug set. When I attempted to join that room, the link was properly constructed to the fallback of `/rooms/1`. However, when I joined the room, it auto-created a room named named "1" with id: 2.

**Comment by bryanrite** [comment]
That is sort of by design... I didn't think we'd mix up auto-generated IDs and named rooms... what happens when you want to name a room "123"... so I thought we'd always just expose the names... and if required, generate a short URL for links.... Where was the "fallback" link generated?

**Comment by bklang** [comment]
I think it should be one way or the other. The problem is that you have code that falls back to IDs when creating links, but then don't respect them when the links are followed.

I think the fallback is OK. In what I just pushed, we always try the slug first. So your example of a room called "123" will still work, even if there is a room with ID 123.

**Comment by bklang** [comment]
@bryanrite to answer your other question, the code to generate fallback links is here: https://github.com/mojolingo/talking_stick/commit/0ccefafe5cc131ce7fd2aee4ce4c07f1c5fdfbd5

**Comment by bryanrite** [comment]
Ah yes... that was just to support existing rooms that had no slug... but since every room created henceforth would have a slug it wouldn't be used... basically for backwards compatibility.. not for falling back.

**Pull request merged**
